### ISSUE TITLE
Thanks! (not an issue, just no other place for this)

### ISSUE THREAD

**Issue by dextersLabRat** [GiorgosXou/under-scroll#1]
Hi. Genius plugin! I just got a huge 34" monitor and find that it's just too huge in portrait mode; I have used a 27" monitor in this way for years, but had thought "there must be a way to split scroll..." So thank you for a really great effort here. I'm gonna have to get used to it, I think, but this really addresses an issue for me. Thanks again!!

**Comment by GiorgosXou** [comment]
I was in quiet the same situation like you where, when I first thought of making this plugin. I was using a 43" TV monitor where I usually had 2 open windows in a row *(VSCode + WebBrowser most of the times)* and even then, I felt like something was missing and that had to be utilized somehow *(plus, I couldn't resist the urge of being able to see more lines of code at the same time, without getting confused of where I am in the code while scrolling up and down repeatedly and so i made it😅)*
 
 #
> "there must be a way to split scroll..." 

"Split-scroll" actually sound kinda better than "under-scroll" now that i'm thinking 😅 ... *(I might consider it as a new name)* *(Also, "under-scroll" reminds me of an old name of a game that i can't remember for some reason 🤔)*

 #
> Genius plugin! ... thank you for a really great effort here... really addresses an issue for me. Thanks again!!

**Thanks you so much for your kind words, you really made my day!** 😊
